# .bash_profile

# Add applicable dirs to path (if they are not there already and they exist)
pathdirs="$HOME/.local/bin /usr/local/bin $HOME/bin $HOME/.yarn/bin $HOME/go/bin/"
for p in $pathdirs; do
    if [[ $PATH != *:$p:* && -d $p ]]; then
        PATH=$PATH:$p
    fi
done
export PATH

# Set vim to default editor
if hash nvim 2> /dev/null; then # Use nvim if we have it
    export VISUAL=nvim
else
    export VISUAL=vim
fi
export EDITOR=$VISUAL

# Get better ls colors on Mac OS
if [[ "$(uname -s)" == "Darwin"  ]]; then
    export LSCOLORS='Exgxcxdxbxegedabagacad'
fi

# Let GPG know we dont have a GUI
export GPG_TTY=$(tty)

# WSL Bash on Windows doesnt apply umask correctly
if [[ "$(umask)" == "0000" ]]; then
    umask 022
fi

# Get the aliases and functions
[[ -f ~/.bashrc ]] && . ~/.bashrc
