#!/bin/bash
# file: ~/.bash_aliases  (sourced from ~/.bashrc)
# author: Christian Fosli <cfosli@gmail.com>
shopt -s expand_aliases

# Get some colors
alias grep='grep --color=auto'

# Cut filenames at 20 characters and make columns:
lc() {
    [[ -z "$1" ]] && set -- "."
    ls "$1" | cut -c1-20 | column -c"${COLUMNS:-80}"
}

# Prettier
prettier() {
    docker run --rm -v "$(pwd)":/work tmknom/prettier "$@"
}


# Fix command like in vim command line window
alias q:=fc

# Alias vi to nvim
alias vi='nvim'

# Print weather to the console
function weather() {
    curl "wttr.in/$1"
}

# Mac / Linux / Windows (git-bash) specific
if [[ "$(uname -s)" == "Darwin" ]]; then     # Mac-only:
    alias see='qlmanage -p &>/dev/null'
    alias ls='ls -G'
elif [[ "$(uname -s)" == "MINGW64"* ]]; then # Git-bash only:
    alias see='start'
    alias py3='winpty python'
    alias pip='winpty pip'
    alias npm='winpty npm.cmd'
else    # Linux-only aliases
    alias ls='ls --color=auto'
    alias ip='ip --color'
    hash ncal 2> /dev/null && alias cal='ncal -bMw' || alias cal='cal -w --monday'
    hash see 2> /dev/null || alias see='xdg-open'
fi
