# bash_profile: executed for login shells

# Add environment variables
set -a
BASH_PROFILE_READ=1 # let .bashrc know this has run
. ~/.config/bash/variables.env
. ~/.config/bash/secrets.env
set +a

# Automatically open ssh-agent
[[ "$(uname -s)" == "Linux"* ]] && [[ "$SSH_AUTH_SOCK" == "" ]] && eval "$(ssh-agent -s)" &&\
ssh-add

# Get the aliases and functions
[[ -f ~/.config/bash/bashrc ]] && . ~/.config/bash/bashrc
