#!/bin/bash
# bash_aliases: sourced from bashrc
shopt -s expand_aliases

alias vi=nvim

alias k=kubectl
complete -F __start_kubectl k

alias weather='curl wttr.in'

# Flatpak run shortcuts
alias postman='flatpak run com.getpostman.Postman'
alias skype='flatpak run com.skype.Client'

# Docker run shortcuts
alias prettier='docker run --rm -v "$(pwd):/work" tmknom/prettier'
alias terraform-compliance='docker run --rm -v "$(pwd):/target" -t eerkunt/terraform-compliance'

# Get some colors
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias ip='ip --color'

# Start calendar on mondays
hash ncal 2> /dev/null && alias cal='ncal -bMw' || alias cal='cal -w --monday'

# ls with long filenames truncated to 20 chars:
lc() {
    ls ${1:-.} | cut -c1-20 | column -c"${COLUMNS:-80}"
}

root_partition_full() {
    sudo journalctl --vacuum-size=100M
    sudo dnf clean all
    docker container prune
    docker image prune
    docker volume prune
    docker builder prune
    echo -e "\n\nFinished cleaning\n\n"
    docker system df
    echo "if docker is still taking a lot of space, consider prune with the '-a' flag"
}

# Open files with default windows app on WSL
if hash pwsh.exe 2> /dev/null; then
    wsl-open() {
        local windowspath="$(wslpath -w $@)" && pwsh.exe -c "start $windowspath";
    }
fi
